### ISSUE TITLE
Tablet support on admin prompt

### ISSUE THREAD

**Issue by C0D3-M4513R** [InfinityGhost/OpenTabletDriver#553] opened 2020-12-13 20:10 UTC
## Description

When OpenTabletDriver is active, the tablet will stop working during a admin permission promt.
More specifically, the mouse will just be frozen in place, when using the tablet as an input source
I would like for that to change, and have OpenTabletDriver work during a admin promt.

Can't record admin elevation promt

**Comment by AbstractQbit** [comment] 2020-12-13 20:11
Duplicate of #347, #469 and #539.

**Comment by X9VoiD** [comment] 2020-12-13 20:12
If you really need input on an elevated process then use kernel-level mode plugins like VMultiMode from VoiDPlugin repo

**Closed** 2020-12-13 20:15 UTC
Labels: duplicate, wontfix

**Comment by C0D3-M4513R** [comment] 2020-12-13 21:54
VmMultiMode may be a good plugin, but it just breaks tablet detection. When I use it, my tablet is just instantly unrecognised

**Comment by X9VoiD** [comment] 2020-12-13 22:12
It *never* affects tablet detection when you've done everything correctly. Make sure you've followed the wiki properly to install vmulti dependency.

**Comment by C0D3-M4513R** [comment] 2020-12-14 17:20
```
Adding driver package:  vmulti.inf
Driver package added successfully. (Already exists in the system)
Published Name:         oem31.inf
Driver package is up-to-date on device: ROOT\HIDCLASS\0000
```
Don't see any issue there...
