### ISSUE TITLE
OTD refuses to interact with specific Microsoft PowerToys windows in any way

### ISSUE THREAD

**Issue by OrionOth** [InfinityGhost/OpenTabletDriver#636] opened 2021-01-08 16:59 UTC
## Description
This is a repost of [PowerToys issue #8975](https://github.com/microsoft/PowerToys/issues/8975). As such, I will paste the bug report below.

------
See notes section at bottom for more information.
## ℹ Computer information

- PowerToys version: 0.29.3
- PowerToy Utility: PowerToys Settings, Color Picker, Fancy Zones Editor
- Running PowerToys as Admin: True
- Windows build number: 19042.685

## 📝 Provide detailed reproduction steps (if any)

1. Start [OpenTabletDriver](https://github.com/InfinityGhost/OpenTabletDriver)
2. Open any of the windows listed below:
- PowerToys Settings
- Color Picker
- Fancy Zones Editor(not the overlay that appears while dragging a window)
3. Attempt to interact with the computer using the tablet. This can include moving the pen or clicking with the buttons.

### ✔️ Expected result

Tablet behavior functions in the same manner as elsewhere on the system (can move cursor, can send button inputs)

### ❌ Actual result

Interaction with the computer via the tablet is completely non-functional and the system appears to not receive input of any sort from the driver.
Can't focus problematic PowerToys windows with tablet pen click. 

## 📷 Screenshots

https://i.vgy.me/mxR090.png
Seen here is the tablet driver receiving pen updates, including clicking. In case it isn't visible enough(which it really isn't), I have the "Dark" radial highlighted. In the case of proper function, the "Dark" radial would be selected.
## Notes 

- Normal mouse interaction is in no way impeded.
- Produced on Wacom CTL-472 running [OpenTabletDriver](https://github.com/InfinityGhost/OpenTabletDriver)
- According to integrated Tablet Debugger, the driver is receiving inputs from the tablet. It would seem that PowerToys is somehow interfering between the driver and the system. 

Related: [PowerToys issue #5946](https://github.com/microsoft/PowerToys/issues/5946)

Request verification with alternate software and/or hardware

------
## System Information:
| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10  Pro 20H2 Build 19042.685
| Software Version | OpenTabletDriver v0.4.2
| Tablet           | Wacom CTL-472

**Comment by X9VoiD** [comment] 2021-01-08 17:06
If it's with tablet input not working then it won't ever be fixed since OTD cannot report input into elevated processes. Duplicate of #347, #469, #539 and #553. Failure to focus PT window through pen input is also a result of OTD running as a user-mode driver.

If you *really* need to inject input into elevated processes then use [VMultiMode](https://github.com/X9VoiD/VoiDPlugins/wiki/VMultiMode) using [OTD 0.5.0](https://discord.com/channels/615607687467761684/615939905566015493/794446989739294780) pre-release.

**Closed** 2021-01-08 18:31 UTC
Labels: duplicate, wontfix
