### ISSUE TITLE
Support For x32 based OS

### ISSUE THREAD

**Issue by oDruvee** [InfinityGhost/OpenTabletDriver#554] opened 2020-12-14 05:03 UTC
I've been hearing some good stuff about this driver, however I think that not everyone has a x64 bit system and therefore I think x32 bit support should be added

**Comment by InfinityGhost** [comment] 2020-12-14 05:11
Duplicate of https://github.com/InfinityGhost/OpenTabletDriver/issues/280, we don't plan on adding support for x86 because its even more to maintain than what we already have. Nothing stops you from building it for Windows x86 however, but there's no guarantee it anything will work. See [this](https://github.com/InfinityGhost/OpenTabletDriver/issues/280#issuecomment-690862950) for build instructions for Windows x86.

**Closed by InfinityGhost** 2020-12-14 05:11 UTC
Labels: duplicate
