### ISSUE TITLE
Instant crash on MacOS (0.5.0)

### ISSUE THREAD

**Issue by VuAnhNoob** [InfinityGhost/OpenTabletDriver#710] opened 2021-01-24 10:55 UTC
## Description

When I open the app it keeps crashing after 1 second and I have already downloaded the .NET 5 Runtime already. I don't know if this is happening with other people but please fix this or tell me why this is happening.
## System Information:

| Name: Nguyen Vu Anh             | Value |
| ---------------- | ----- |
| Operating System | MacOS
| Software Version |High Sierra
| Tablet           |Wacom CTL 4100

**Comment by InfinityGhost** [comment] 2021-01-25 01:27
This is a known bug, try [this build](https://cdn.discordapp.com/attachments/615939905566015493/802310814202593290/OpenTabletDriver.osx-x64.tar.gz)

**Comment by InfinityGhost** [comment] 2021-01-25 01:28
Duplicate of #690

**Closed** 2021-01-27 04:24 UTC
Labels: bug, duplicate
