### ISSUE TITLE
G640: Failed to open tablet.

### ISSUE THREAD

**Issue by skyborgff** [InfinityGhost/OpenTabletDriver#133] opened 2020-05-13 19:11 UTC
## Description
[Error:Detect]	Failed to open tablet. Make sure you have required permissions to open device streams.
[Error:Detect]	HidSharp.Exceptions.DeviceIOException: Unable to open HID class device (\\?\hid#vid_28bd&pid_0914&mi_00&col03#9&7e5db84&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd).
   at HidSharp.Platform.Windows.WinHidStream.Init(String path)
   at HidSharp.Platform.Windows.WinHidDevice.OpenDeviceDirectly(OpenConfiguration openConfig)
   at HidSharp.Device.OpenDeviceAndRestrictAccess(OpenConfiguration openConfig)
   at HidSharp.Device.Open(OpenConfiguration openConfig)
   at HidSharp.Device.TryOpen(OpenConfiguration openConfig, DeviceStream& stream, Exception& exception); Retrying 1 more times

## System Information:
------------------|------------------
Operating System  | 10
Software Version  | v0.2.0-rc1
Tablet            | G640

**Comment by InfinityGhost** [comment] 2020-05-13 22:17
Duplicate of #132

**Closed by InfinityGhost** 2020-05-13 22:17 UTC
Labels: duplicate
