### ISSUE TITLE
The installer will not launch without admin privileges.

### ISSUE THREAD

**Issue by adxv** [InfinityGhost/OpenTabletDriver#767] opened 2021-02-12 15:02 UTC
The issue is likely caused by having the UAC disabled.

Workaround: Create a bat file with the following command(replace the location of the installer): 
`runas /trustlevel:0x20000 C:\Users\adams\Downloads\OpenTabletDriver.Installer.exe`

**Comment by AbstractQbit** [comment] 2021-02-12 15:09
This is looks like a duplicate of #681.

**Comment by adxv** [comment] 2021-02-12 15:23
Thank you and sorry.

**Closed** 2021-02-12 15:23 UTC
